<a href="https://colab.research.google.com/github/joshimohitm9/Feature-Engineering/blob/main/K_fold_cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
digits=load_digits()
dir(digits)
import warnings
warnings.filterwarnings("ignore")

In [ ]:
x=pd.DataFrame(digits["data"],columns=digits["feature_names"])
y=pd.DataFrame(digits["target"],columns=["target"])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9648148148148148

In [ ]:
svm=SVC(kernel="linear")
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.975925925925926

In [ ]:
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9703703703703703

In [ ]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

0.8537037037037037

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
def mohit(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)


In [ ]:
mohit(rf,x_train,x_test,y_train,y_test)

0.9703703703703703

In [ ]:
mohit(svm,x_train,x_test,y_train,y_test)

0.975925925925926

In [ ]:
mohit(lr,x_train,x_test,y_train,y_test)

0.9648148148148148

In [ ]:
mohit(dt,x_train,x_test,y_train,y_test)

0.8574074074074074

In [ ]:
abc=[lr,rf,dt,svm]
for i in abc:
  print(i)
  i.fit(x_train,y_train)
  print(i.score(x_test,y_test))
  print("__________________")


LogisticRegression()
0.9648148148148148
__________________
RandomForestClassifier()
0.9796296296296296
__________________
DecisionTreeClassifier()
0.8296296296296296
__________________
SVC(kernel='linear')
0.975925925925926
__________________


In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
abc=[lr,rf,dt,svm]
for i in abc:
  print(i)
  print(cross_val_score(i,x_train,y_train,cv=5))
  print("__AVERAGE___")
  print(np.average(cross_val_score(i,x_train,y_train,cv=5)))
  print("_____________________________________________________")


LogisticRegression()
[0.96428571 0.95634921 0.96015936 0.9561753  0.94820717]
__AVERAGE___
0.9570353506608488
_____________________________________________________
RandomForestClassifier()
[0.98015873 0.96825397 0.96414343 0.97609562 0.9561753 ]
__AVERAGE___
0.9681685954594321
_____________________________________________________
DecisionTreeClassifier()
[0.80952381 0.81746032 0.80478088 0.87649402 0.8247012 ]
__AVERAGE___
0.8289729969012838
_____________________________________________________
SVC(kernel='linear')
[0.99206349 0.99603175 0.98406375 0.98007968 0.96812749]
__AVERAGE___
0.9840732308859799
_____________________________________________________


In [ ]:
from sklearn.model_selection import cross_val_score
a=cross_val_score(lr,x_train,y_train)
print(a)
print("__avg__")
np.average(a)


[0.96428571 0.95634921 0.96015936 0.9561753  0.94820717]
__avg__


0.9570353506608488